# pilot completion                                         -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_pilot_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  if [[ "${cur:0:1}" == "-" ]]; then
    echo "$words"

  else
    for word in $words; do
      [[ "${word:0:1}" != "-" ]] && result+=("$word")
    done

    echo "${result[*]}"

  fi
}

_pilot_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
  local compline="${compwords[*]}"

  case "$compline" in
    'intune'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_pilot_completions_filter "--help --verbose -h -v")" -- "$cur")
      ;;

    'docker'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_pilot_completions_filter "--help --verbose -h -v")" -- "$cur")
      ;;

    'incus'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_pilot_completions_filter "--help --verbose -h -v")" -- "$cur")
      ;;

    *)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_pilot_completions_filter "--help --version -h -v docker incus intune")" -- "$cur")
      ;;

  esac
} &&
  complete -F _pilot_completions pilot

# ex: filetype=sh
